# This workflow will upload a Docker container

name: Build/Upload Docker Container

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - 'master'
  pull_request:

env:
  CONTAINER_NAME: qmk/base_container
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/master

      - name: Log in to Docker Hub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: ${{ (github.ref == 'refs/heads/master' && 'linux/amd64, linux/arm64') || 'linux/amd64' }}
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ env.CONTAINER_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

